<?php
if (session_status() === PHP_SESSION_NONE) session_start(); $current_page=basename($_SERVER['PHP_SELF']); $logged_in=isset($_SESSION['user_id']);
function icon_svg($name){$icons=['calendar'=>'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>','event'=>'<path d="M4 4h16v5a2 2 0 0 0 0 4v5H4v-5a2 2 0 0 0 0-4z"/><path d="M12 7v8"/>','food'=>'<path d="M7 3v8M4 3v5a3 3 0 0 0 6 0V3M7 11v10M17 3v18M17 3c3 2 3 7 0 9"/>','cart'=>'<circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M2 3h3l2.4 12h11.8l2-8H6"/>','car'=>'<path d="M5 17h14M6 17l-1-5 2-5h10l2 5-1 5M7 17v2M17 17v2"/><circle cx="7" cy="14" r="1"/><circle cx="17" cy="14" r="1"/>','tradition'=>'<path d="M12 3l2.2 5.5L20 10l-4.5 3.8 1.4 5.7-4.9-3-4.9 3 1.4-5.7L4 10l5.8-1.5z"/>','camera'=>'<path d="M4 7h4l2-3h4l2 3h4v13H4z"/><circle cx="12" cy="13" r="3.5"/>','bookmark'=>'<path d="M6 3h12v18l-6-4-6 4z"/>','dashboard'=>'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>'];return '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'.$icons[$name].'</svg>';}
$navigation=['festivals.php'=>['calendar','Festival Calendar'],'events.php'=>['event','Festival Events'],'food.php'=>['food','Traditional Food'],'shopping.php'=>['cart','Shopping Guide'],'travel.php'=>['car','Travel & Transport'],'traditions.php'=>['tradition','Cultural Traditions'],'albums.php'=>['camera','Festival Memories']];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>RonginBD</title><link rel="stylesheet" href="/RonginBD/assets/css/style.css"><link rel="stylesheet" href="/RonginBD/assets/css/week2.css"><link rel="stylesheet" href="/RonginBD/assets/css/final-fixes.css"></head><body>
<header class="topbar"><a class="brand" href="/RonginBD/index.php">Rongin<span>BD</span></a><nav><?php if($logged_in):?><a class="header-action <?= $current_page==='bookmarks.php'?'active':'' ?>" href="/RonginBD/pages/bookmarks.php" title="Bookmarks"><?=icon_svg('bookmark')?><span>Bookmarks</span></a><a class="header-action <?= $current_page==='dashboard.php'?'active':'' ?>" href="/RonginBD/pages/dashboard.php" title="My Dashboard"><?=icon_svg('dashboard')?><span>Dashboard</span></a><span class="welcome"><?=htmlspecialchars($_SESSION['user_id'])?></span><a class="logout" href="/RonginBD/auth/logout.php">Log out</a><?php else:?><a href="/RonginBD/auth/login.php">Log in</a><a class="button small" href="/RonginBD/auth/register.php">Register</a><?php endif;?></nav></header>
<div class="app-shell"><aside><p class="menu-label">DISCOVER</p><?php foreach($navigation as $file=>$nav_item):?><a class="<?=$current_page===$file?'active':''?>" href="/RonginBD/pages/<?=$file?>"><span class="nav-icon"><?=icon_svg($nav_item[0])?></span><?=$nav_item[1]?></a><?php endforeach;?></aside><main>
<?php if(isset($_GET['message'])):?><div class="notice success"><?=htmlspecialchars($_GET['message'])?></div><?php endif;?><?php if(isset($_GET['error'])):?><div class="notice error"><?=htmlspecialchars($_GET['error'])?></div><?php endif;?>
